version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "9999:9999"
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: 'develop-stage'
    ports:
    - '80:8080'
    volumes:
    - './frontend/:/app'
    command: /bin/sh -c "npm run serve"